config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("restaurants/", include("restaurants.urls", namespace="restaurants")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from restaurants import views as restaurant_views

app_name = "core"

urlpatterns = [
    path("", restaurant_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path(
        "toggle/<int:restaurant_pk>", views.toggle_restaurant, name="toggle-restaurant"
    ),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

reviews/urls.py
from django.urls import path
from . import views


app_name = "reviews"

urlpatterns = [path("create/<int:restaurant>", views.create_review, name="create")]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
    path("guest/<int:pk>/", views.show_guest_reservation, name="guest-reservation"),
    path(
        "host/<int:pk>/",
        views.show_host_reservation,
        name="host-reservation",
    ),
    path("<int:pk>/photos/", views.UserPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:user_pk>/photos/<int:photo_pk>/delete",
        views.delete_photo,
        name="delete-photo",
    ),
]

templates/partials/footer.html
{% load i18n %}
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-500">
    <div class="flex flex-col">
        <span>
            {% trans "Please don't copy us." %}
        </span>
        <span>&copy; 2020 SuTongCom. {% trans "All rights reserved" %}.</span>
    </div>
    <div class="flex-1 w-64">
        {% get_current_language as LANGUAGE_CODE %}
        <select
            class="block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py- pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline"
            id="js-lang">
            <option value="en" {% if LANGUAGE_CODE == 'en' %} selected {% endif %}>English</option>
            <option value="ko" {% if LANGUAGE_CODE == 'ko' %} selected {% endif %}>한국어</option>
        </select>
    </div>
</footer>

templates/partials/messages.html
{% if messages %}
<ul class="absolute top-0 mx-auto left-0 right-0 flex justify-center">
    {% for message in messages %}
    <li
        class="message font-medium bg-gray-700 z-10 rounded-full text-white py-4 px-6 w-3/12 text-center {% if message.tags %}{{ message.tags }}{% endif %}">
        {{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
{% load i18n %}
<ul class="flex items-center text-sm font-medium h-full">
    {% if user.is_authenticated %}
    <li class="nav_link">
        <a href="{% url 'users:switch-hosting' %}">
            {% if request.session.is_hosting %}
            {% trans "Stop hosting" %}
            {% else %}
            {% trans "Start hosting" %}
            {% endif %}
        </a>
    </li>
    {% if request.session.is_hosting %}
    <li class="nav_link"><a href="{% url "restaurants:create" %}">{% trans "Create a Restaurant" %}</a></li>
    {% endif %}

    {% if request.session.is_hosting %}
    <li class="nav_link"><a href="{% url "users:host-reservation" user.pk %}">{% trans "My Reservation(for Host)" %}</a>
    </li>
    {% else %}
    <li class="nav_link"><a
            href="{% url "users:guest-reservation" user.pk %}">{% trans "My Reservation(for Guest)" %}</a>
    </li>
    {% endif %}

    <li class="nav_link"><a href="{% url "lists:see-favs" %}">{% trans "Favorites" %}
            {% if user.list.restaurants.count %}
            ({{user.list.restaurants.count}})
            {% else %}
            (0)
            {% endif %}
        </a>
    </li>
    <li class="nav_link"><a href="{{user.get_absolute_url}}">{% trans "Profile" %}</a></li>
    <li class="nav_link"><a href="{% url "users:logout" %}">{% trans "Log out" %}</a></li>
    {% else %}
    <li class="nav_link"><a href="{% url "users:login" %}">{% trans "Log in" %}</a></li>
    <li class="nav_link"><a href="{% url "users:signup" %}">{% trans "Sign up" %}</a></li>
    {% endif %}
</ul>

templates/partials/social_login.html
{% load static i18n %}
<div class="flex flex-col w-full">


    <a href="{% url 'users:kakao-login' %}" class="btn border-2 border-gray-700 text-yellow-900 bg-yellow-400 mb-2">
        <i class="fas fa-comment mr-2 fa-lg"></i>{% trans "Log in with Kakao"%}
    </a>

</div>

<div class="flex items-center w-full my-5">
    <div class="h-px w-full bg-gray-400"></div>
    <span class="text-gray-600 font-medium mx-4 text-sm">or</span>
    <div class="h-px w-full bg-gray-400"></div>
</div>