config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("restaurants/", include("restaurants.urls", namespace="restaurants")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from restaurants import views as restaurant_views

app_name = "core"

urlpatterns = [
    path("", restaurant_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path(
        "toggle/<int:restaurant_pk>", views.toggle_restaurant, name="toggle-restaurant"
    ),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "<int:restaurant>/<int:year>-<int:month>-<int:day>/",
        views.choose_detail,
        name="choose-detail",
    ),
    path(
        "<int:restaurant>/<int:year>-<int:month>-<int:day>-<str:time>/<int:numOfGuests>",
        views.create,
        name="create",
    ),
    path("<int:pk>/", views.reservation_detail, name="detail",),
    path("<int:pk>/<str:verb>/", views.edit_reservation, name="edit"),
]

restaurants/urls.py
from django.urls import path
from . import views

app_name = "restaurants"

urlpatterns = [
    path("create/", views.CreateRestaurantView.as_view(), name="create"),
    path("<int:pk>", views.RestaurantDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRestaurantView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RestaurantPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:restaurant_pk>/photos/<int:photo_pk>/delete",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:restaurant_pk>/photos/<int:photo_pk>/edit",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

restaurants/forms.py
from django import forms
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(required=True)
    name = forms.CharField(required=False)
    guests = forms.IntegerField(required=False)
    service_options = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.ServiceOptions.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    highlights = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Highlights.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    accessibilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Accessibility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    offerings = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Offerings.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    dining_options = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.DiningOptions.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenities.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    atmosphere = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Atmosphere.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    crowd = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Crowd.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    planning = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Planning.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    payments = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Payments.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        restaurant = models.Restaurant.objects.get(pk=pk)
        photo.restaurant = restaurant
        photo.save()


class CreateRestaurantForm(forms.ModelForm):
    class Meta:
        model = models.Restaurant
        fields = (
            "name",
            "description",
            "city",
            "address",
            "guests",
            "service_options",
            "highlights",
            "accessibilities",
            "offerings",
            "dining_options",
            "amenities",
            "atmosphere",
            "crowd",
            "planning",
            "payments",
            "menu_1",
            "price_1",
            "menu_2",
            "price_2",
            "menu_3",
            "price_3",
            "menu_4",
            "price_4",
            "menu_5",
            "price_5",
        )

    def save(self, *args, **kwargs):
        restaurant = super().save(commit=False)
        return restaurant

restaurants/views.py
from django.http import Http404
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from users import mixins as user_mixins
from . import models, forms


class HomeView(ListView):

    """ HomeView Definition """

    model = models.Restaurant
    paginate_by = 12
    paginate_orphans = 0
    ordering = "created"
    context_object_name = "restaurants"


class RestaurantDetail(DetailView):

    """ RestaurantDetail Definition """

    model = models.Restaurant


class SearchView(View):

    """ SearchView Definition """

    def get(self, request):

        city = request.GET.get("city")
        city = str.capitalize(city)

        if city:
            form = forms.SearchForm(request.GET)
            if form.is_valid():
                name = form.cleaned_data.get("name")
                name = str.capitalize(name)
                guests = form.cleaned_data.get("guests", 0)
                service_options = form.cleaned_data.get("service_options")
                highlights = form.cleaned_data.get("highlights")
                accessibilities = form.cleaned_data.get("accessibilities")
                offerings = form.cleaned_data.get("offerings")
                dining_options = form.cleaned_data.get("dining_options")
                amenities = form.cleaned_data.get("amenities")
                atmospheres = form.cleaned_data.get("atmosphere")
                crowds = form.cleaned_data.get("crowd")
                plannings = form.cleaned_data.get("planning")
                payments = form.cleaned_data.get("payments")
                print(city)
                print(name)

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__contains"] = city

                if name != "None":
                    filter_args["name__contains"] = name

                if guests is not None:
                    filter_args["guests__lte"] = guests

                for service_option in service_options:
                    filter_args["service_options"] = service_option

                for highlight in highlights:
                    filter_args["highlights"] = highlight

                for accessibility in accessibilities:
                    filter_args["accessibilities"] = accessibility

                for offering in offerings:
                    filter_args["offerings"] = offering

                for dining_option in dining_options:
                    filter_args["dining_options"] = dining_option

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for atmosphere in atmospheres:
                    filter_args["atmosphere"] = atmosphere

                for crowd in crowds:
                    filter_args["crowd"] = crowd

                for planning in plannings:
                    filter_args["planning"] = planning

                for payment in payments:
                    filter_args["payments"] = payment

                restaurants = models.Restaurant.objects.filter(**filter_args)

                return render(
                    request,
                    "restaurants/search.html",
                    {"form": form, "restaurants": restaurants},
                )
        else:
            form = forms.SearchForm()

        return render(
            request,
            "restaurants/search.html",
            {"form": form},
        )


class EditRestaurantView(user_mixins.LoggedInOnlyView, UpdateView):

    model = models.Restaurant
    template_name = "restaurants/restaurant_edit.html"
    fields = (
        "name",
        "description",
        "city",
        "address",
        "guests",
        "service_options",
        "highlights",
        "accessibilities",
        "offerings",
        "dining_options",
        "amenities",
        "atmosphere",
        "crowd",
        "planning",
        "payments",
        "menu_1",
        "price_1",
        "menu_2",
        "price_2",
        "menu_3",
        "price_3",
        "menu_4",
        "price_4",
        "menu_5",
        "price_5",
    )

    def get_object(self, queryset=None):
        restaurant = super().get_object(queryset=queryset)
        if restaurant.host.pk != self.request.user.pk:
            raise Http404()
        return restaurant


class RestaurantPhotosView(user_mixins.LoggedInOnlyView, DetailView):

    model = models.Restaurant
    template_name = "restaurants/restaurant_photos.html"

    def get_object(self, queryset=None):
        restaurant = super().get_object(queryset=queryset)
        if restaurant.host.pk != self.request.user.pk:
            raise Http404()
        return restaurant


@login_required
def delete_photo(request, restaurant_pk, photo_pk):
    user = request.user
    try:
        restaurant = models.Restaurant.objects.get(pk=restaurant_pk)
        if restaurant.host.pk != user.pk:
            messages.error(request, _("Can't delete that photo"))
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, _("Photo Deleted"))
        return redirect(reverse("restaurants:photos", kwargs={"pk": restaurant_pk}))
    except models.Restaurant.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Photo
    template_name = "restaurants/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = _("Photo Updated")
    fields = ("caption",)

    def get_success_url(self):
        restaurant_pk = self.kwargs.get("restaurant_pk")
        return reverse("restaurants:photos", kwargs={"pk": restaurant_pk})


class AddPhotoView(user_mixins.LoggedInOnlyView, FormView):

    template_name = "restaurants/photo_create.html"
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, _("Photo Uploaded"))
        return redirect(reverse("restaurants:photos", kwargs={"pk": pk}))


class CreateRestaurantView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreateRestaurantForm
    template_name = "restaurants/restaurant_create.html"

    def form_valid(self, form):
        restaurant = form.save()
        restaurant.host = self.request.user
        restaurant.save()
        form.save_m2m()
        messages.success(self.request, "Restaurant Uploaded")
        return redirect(reverse("restaurants:detail", kwargs={"pk": restaurant.pk}))

templates/restaurants/photo_create.html
{% extends "base.html" %}

{% block page_title %}
Upload Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">


    {% include 'mixins/auth/auth_form.html' with form=form cta="Upload photo" %}


</div>
{% endblock content %}

templates/restaurants/photo_edit.html
{% extends "base.html" %}

{% block page_title %}
Update Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">


    {% include 'mixins/auth/auth_form.html' with form=form cta="Update photo" %}


</div>
{% endblock content %}

templates/restaurants/restaurant_create.html
{% extends "base.html" %}

{% block page_title %}
Create Restaurant
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">


    {% include 'mixins/auth/auth_form.html' with form=form cta="Create" %}


</div>
{% endblock content %}

templates/restaurants/restaurant_detail.html
{% extends "base.html" %}
{% load is_booked on_favs i18n %}

{% block page_title %}
{{restaurant.name}}
{% endblock page_title %}

{% block content %}

<div class="-mt-5 container max-w-full h-75vh flex mb-20">
    <div class="h-full w-1/2 bg-center bg-cover" style="background-image:url({{restaurant.first_photo}})"></div>
    <div class="h-full w-1/2 flex flex-wrap">
        {% for photo in restaurant.get_next_four_photos %}
        <div style="background-image:url({{photo.file.url}})"
            class="w-1/2 h-auto bg-cover bg-center border-gray-700 border"></div>
        {% endfor %}
    </div>
</div>

<div class="container mx-auto flex justify-around pb-56">
    <div class="w-1/2">
        <div class="flex justify-between">
            <div class="mb-5">
                <h4 class="text-3xl font-medium mb-px">{{restaurant.name}}</h4>
                <span class="text-gray-700 font-light">{{restaurant.address}}</span>
            </div>
            <a href="{{restaurant.host.get_absolute_url}}" class="flex flex-col items-center">
                {% include "mixins/user_avatar.html" with user=restaurant.host %}
                <span class="mt-2 text-gray-500">{{restaurant.host.first_name}}</span>
            </a>
        </div>
        {% on_favs restaurant as on_favs_boolean %}
        {% if on_favs_boolean %}
        <a class="block mb-10 w-2/6 text-teal-600 font-bold"
            href="{% url 'lists:toggle-restaurant' restaurant.pk %}?action=remove">{% trans "Delete from Favourites" %}</a>
        {% else %}
        <a class="block mb-10 w-2/6 text-teal-600 font-bold"
            href="{% url 'lists:toggle-restaurant' restaurant.pk %}?action=add">{% trans "Add to Favourites" %}</a>
        {% endif %}

        <p class="border-section">
            {{restaurant.description}}
        </p>
        <div class="flex border-section">
            <span class="mr-5 font-light">
                {{restaurant.guests}} {% trans "guests" %}</span>
        </div>


        <div>
            <div class="grid md:grid-cols-2 sm:grid-cols-1 lg:grid-cols-2 m-5 mb-10">
                <div class="bg-white overflow-hidden hover:bg-green-100 border border-gray-200 p-1">
                    <h4 class="font-medium text-lg mb-5">Highlights</h4>
                    {% for a in restaurant.highlights.all %}
                    <li class="mb-2">{{a}}</li>
                    {% endfor %}
                </div>
                <div class="bg-white overflow-hidden hover:bg-green-100 border border-gray-200 p-3">
                    <h4 class="font-medium text-lg mb-5">Accessibility</h4>
                    {% for a in restaurant.accessibilities.all %}
                    <li class="mb-2">{{a}}</li>
                    {% endfor %}
                </div>
                <div class="bg-white overflow-hidden hover:bg-green-100 border border-gray-200 p-3">
                    <h4 class="font-medium text-lg mb-5">Offerings</h4>
                    {% for a in restaurant.offerings.all %}
                    <li class="mb-2">{{a}}</li>
                    {% endfor %}
                </div>
                <div class="bg-white overflow-hidden hover:bg-green-100 border border-gray-200 p-3">
                    <h4 class="font-medium text-lg mb-5">Dining Options</h4>
                    {% for a in restaurant.dining_options.all %}
                    <li class="mb-2">{{a}}</li>
                    {% endfor %}
                </div>
                <div class="bg-white overflow-hidden hover:bg-green-100 border border-gray-200 p-3">
                    <h4 class="font-medium text-lg mb-5">Amenities</h4>
                    {% for a in restaurant.amenities.all %}
                    <li class="mb-2">{{a}}</li>
                    {% endfor %}
                </div>
                <div class="bg-white overflow-hidden hover:bg-green-100 border border-gray-200 p-3">
                    <h4 class="font-medium text-lg mb-5">Atmosphere</h4>
                    {% for a in restaurant.atmosphere.all %}
                    <li class="mb-2">{{a}}</li>
                    {% endfor %}
                </div>
                <div class="bg-white overflow-hidden hover:bg-green-100 border border-gray-200 p-3">
                    <h4 class="font-medium text-lg mb-5">Crowd</h4>
                    {% for a in restaurant.crowd.all %}
                    <li class="mb-2">{{a}}</li>
                    {% endfor %}
                </div>
                <div class="bg-white overflow-hidden hover:bg-green-100 border border-gray-200 p-3">
                    <h4 class="font-medium text-lg mb-5">Planning</h4>
                    {% for a in restaurant.planning.all %}
                    <li class="mb-2">{{a}}</li>
                    {% endfor %}
                </div>
                <div class="bg-white overflow-hidden hover:bg-green-100 border border-gray-200 p-3">
                    <h4 class="font-medium text-lg mb-5">Payments</h4>
                    {% for a in restaurant.payments.all %}
                    <li class="mb-2">{{a}}</li>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="mt-10">
            <h4 class="font-medium text-2xl mb-5">{%trans "Reviews"%}</h4>
            <div class="flex items-center">
                <div>
                    <i class="fas fa-star text-teal-500"></i>
                    <span class="font-bold text-xl">{{restaurant.total_rating}}</span>
                </div>
                <div class="h-4 w-px bg-gray-400 mx-5"></div>
                <div>
                    <span class="font-bold text-xl">{{restaurant.reviews.count}}</span>
                    <span>{% trans "reviews" %}</span>
                </div>
            </div>
            <div class="mt-10">
                {% for review in restaurant.reviews.all  %}
                <div class="border-section">
                    <div class="mb-3 flex">
                        <div>
                            {% include "mixins/user_avatar.html" with user=review.user h_and_w='w-10 h-10' text='text-xl' %}
                        </div>
                        <div class="flex flex-col ml-5">
                            <span class="font-medium">{{review.user.first_name}}</span>
                            <span class="text-sm text-gray-500">{{review.created|date:'F Y'}}</span>
                        </div>
                    </div>
                    <p>{{review.review}}</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="w-1/3">
        {% if restaurant.host == user %}
        <a href="{% url 'restaurants:edit' restaurant.pk %}" class="btn-link block">{%trans "Edit Restaurant"%}</a>
        {% else %}
        {% if not request.session.is_hosting %}
        {% for calendar in restaurant.get_calendars %}
        <div class="mb-20">
            <span class="text-center font-semibold text-lg block mb-8">{{calendar.get_month}} / {{calendar.year}}</span>
            <div class="cal-grid font-medium mb-4">
                {% for day in calendar.day_names  %}
                <span>{{day}}</span>
                {% endfor %}
            </div>
            <div class="cal-grid">
                {% for date in calendar.get_days %}
                {% is_booked restaurant date time as is_booked_bool %}
                {% if date.day != 0 %}
                {% if date.past %}
                <span class="cal-number bg-gray-200 text-gray-400">{{date}}</span>
                {% elif is_booked_bool %}
                <span class="cal-number bg-gray-200 text-gray-400 line-through">{{date}}</span>
                {% else %}
                <a href="{% url 'reservations:choose-detail' restaurant.pk date.year date.month date.day %}"
                    class="cal-number bg-gray-200 text-gray-700 hover:bg-teal-400 hover:text-white hover:font-medium">{{date}}</a>
                {% endif %}
                {% else %}
                <span></span>
                {% endif %}
                {% endfor %}
            </div>
        </div>


        {% endfor %}
        {% endif %}
        {% endif %}

        <div class="my-5 w-full">
            <div class="border border-gray-700 rounded-lg">
                <span class="p-3 text-center font-semibold text-lg block">{%trans "Best Menu"%}</span>
                <div class="grid md:grid-cols-2 sm:grid-cols-1 lg:grid-cols-2 mb-3">
                    <div class=" text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                        {{restaurant.menu_1}}
                    </div>
                    <div class="text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                        {{restaurant.price_1}}
                    </div>
                </div>
                <div class="grid md:grid-cols-2 sm:grid-cols-1 lg:grid-cols-2 mb-3">
                    <div class=" text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                        {{restaurant.menu_2}}
                    </div>
                    <div class="text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                        {{restaurant.price_2}}
                    </div>
                </div>
                <div class="grid md:grid-cols-2 sm:grid-cols-1 lg:grid-cols-2 mb-3">
                    <div class=" text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                        {{restaurant.menu_3}}
                    </div>
                    <div class="text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                        {{restaurant.price_3}}
                    </div>
                </div>
                <div class="grid md:grid-cols-2 sm:grid-cols-1 lg:grid-cols-2 mb-3">
                    <div class=" text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                        {{restaurant.menu_4}}
                    </div>
                    <div class="text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                        {{restaurant.price_4}}
                    </div>
                </div>
                <div class="grid md:grid-cols-2 sm:grid-cols-1 lg:grid-cols-2 mb-3">
                    <div class=" text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                        {{restaurant.menu_5}}
                    </div>
                    <div class="text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                        {{restaurant.price_5}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/restaurants/restaurant_edit.html
{% extends "base.html" %}
{% load static i18n %}
{% block page_title %}
Update Restaurant
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">


    {% include 'mixins/auth/auth_form.html' with form=form cta="Update restaurant" %}
    <div class="mt-5">
        <a href="{% url 'restaurants:photos' restaurant.pk %}"
            class="text-teal-500 font-medium">{% trans "Edit Photos" %}</a>
    </div>

</div>
{% endblock content %}

templates/restaurants/restaurant_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block page_title %}
Home
{% endblock page_title %}

{% block content %}

<div class="container mx-auto pb-10">

    <div class="rounded-xl bg-gray-800  -mx-40  h-50vh mt-32 mb-24 bg-cover bg-center"
        style="background-image:url({% static 'img/background.jpg' %});"></div>

    <div class="flex flex-wrap -mx-40 mb-10">
        {% for restaurant in restaurants  %}
        {% include 'mixins/restaurant_card.html' with restaurant=restaurant %}
        {% endfor %}
    </div>
    <div class="flex items-center justify-center mx-auto container">
        {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}" class="text-teal-500">
            <i class="fas fa-arrow-left fa-lg"></i>
        </a>
        {% endif %}

        <span class="mx-3 font-medium text-lg">
            Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
        </span>

        {% if page_obj.has_next  %}
        <a href="?page={{page_obj.next_page_number}}" class="text-teal-500">
            <i class="fas fa-arrow-right fa-lg"></i>
        </a>
        {% endif %}


    </div>

</div>
{% endblock content %}

templates/restaurants/restaurant_photos.html
{% extends "base.html" %}
{% load static i18n %}
{% block page_title %}
{{restaurant.name}}'s Photos
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container mx-auto my-10 flex flex-col">
    <div class="my-10 w-full">
        <a href="{% url 'restaurants:add-photo' restaurant.pk %}"
            class="btn-link w-1/6 block">{%trans "Upload Photo"%}</a>
    </div>


    {% for photo in restaurant.photos.all %}
    <div class="mb-5 border p-6 gorder-gray-400 flex justify-between">
        <div class="flex items-start">
            <img src="{{photo.file.url}}" class="w-32 h-32" />
            <span class="ml-5 text-xl">{{photo.caption}}</span>
        </div>
        <div class=" flex flex-col w-1/5">
            <a class="btn-link mb-5 bg-teal-500"
                href="{% url 'restaurants:edit-photo' restaurant.pk photo.pk %}">Edit</a>
            <a class="btn-link bg-red-700"
                href="{% url 'restaurants:delete-photo' restaurant.pk photo.pk %}">{%trans "Delete"%}</a>
        </div>
    </div>
    {% endfor %}

    <div class="flex justify-center mt-5">
        <a href="{% url 'restaurants:edit' restaurant.pk %}" class="text-teal-500 font-medium text-2xl">
            {%trans "Back to edit restaurant"%}
        </a>
    </div>

</div>
{% endblock content %}

templates/restaurants/search.html
{% extends "base.html" %}
{% load static i18n %}
{% block page_title %}
Search
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class="-mx-3 md:flex mb-6">
    <div class="md:w-1/3 px-3 mb-6 md:mb-0 container w-auto flex-auto items-start border p-6 border-gray-400"
        style="margin-right: 10px; margin-left: 100px;">
        <h3 class="mb-2 text-2xl">{%trans "Search"%}</h3>
        <span class="mt-3 mb-2 text-sm text-gray-500">{%trans "Use filters"%}</span>
        <form method="get" action="{% url "restaurants:search" %}">
            {{form.as_p}}
            <button class="btn bg-red-500 text-white mt-5">{%trans "Search"%}</button>
        </form>
    </div>

    <div class="md:w-2/3 px-6 container mx-auto pb-10 flex flex-col items-start border p-6 border-gray-400"
        style="margin-right: 100px; margin-left: 10px;">
        <h3 class="text-2xl">{%trans "Results"%}</h3>
        <span class="mt-3 text-sm text-gray-500">
            {%if restaurants.count %}
            {{restaurants.count}}
            {%else%}
            0
            {%endif%}
            {%trans "restaurants"%}
        </span>
        <div class="grid gap-2 w-full grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 mt-1">
            {% for restaurant in restaurants %}
            <div class="w-full max-w-sm mx-auto rounded-md shadow-md overflow-hidden">
                <a href="{% url 'restaurants:detail' restaurant.pk %}">
                    <div class="flex items-end justify-end h-56 w-full bg-cover"
                        style="background-image: url({{restaurant.first_photo}});">
                    </div>
                    <div class="flex justify-between mb-2 mx-5 my-2">
                        <div class="w-4/5 block truncate overflos-hidden flex">
                            <span class="text-sm text-gray-600 block truncate font-light">{{restaurant.city}}</span>
                        </div>

                        <span class="text-sm flex items-center">
                            <i class="fas fa-star text-red-500 text-xs mr-px"></i> {{restaurant.total_rating}}
                        </span>

                    </div>

                    <span class="text-black w-11/12 block truncate mx-5 my-2">
                        {{restaurant.name}}
                    </span>

                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock content %}