config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("restaurants/", include("restaurants.urls", namespace="restaurants")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views

app_name = "conversations"

urlpatterns = [
    path("go/<int:a_pk>/<int:b_pk>", views.go_conversation, name="go"),
    path("<int:pk>/", views.ConversationDetailView.as_view(), name="detail"),
]

core/urls.py
from django.urls import path

from restaurants import views as restaurant_views

app_name = "core"

urlpatterns = [
    path("", restaurant_views.HomeView.as_view(), name="home"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "<int:restaurant>/<int:year>-<int:month>-<int:day>/",
        views.choose_detail,
        name="choose-detail",
    ),
    path(
        "<int:restaurant>/<int:year>-<int:month>-<int:day>-<str:time>/<int:numOfGuests>",
        views.create,
        name="create",
    ),
    path("<int:pk>/", views.reservation_detail, name="detail",),
    path("<int:pk>/<str:verb>/", views.edit_reservation, name="edit"),
]

reservations/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from core import models as core_models


class BookedDay(core_models.TimeStampedModel):

    date = models.DateField()
    time = models.CharField(max_length=6, default="00:00")
    reservation = models.ForeignKey("Reservation", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.date)


class Reservation(core_models.TimeStampedModel):

    """ Reservation Model Definition """

    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELED = "canceled"

    STATUS_CHOICES = (
        (STATUS_PENDING, _("Pending")),
        (STATUS_CONFIRMED, _("Confirmed")),
        (STATUS_CANCELED, _("Canceled")),
    )

    status = models.CharField(
        max_length=12, choices=STATUS_CHOICES, default=STATUS_PENDING
    )

    date = models.DateField()

    time = models.CharField(max_length=6, default="00:00")

    guest = models.ForeignKey(
        "users.User", related_name="reservations", on_delete=models.CASCADE
    )

    numOfGuests = models.IntegerField(default=1)

    restaurant = models.ForeignKey(
        "restaurants.Restaurant", related_name="reservations", on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.restaurant} - {self.date}"

    def in_progress(self):
        now = timezone.now().date()
        return now <= self.date

    in_progress.boolean = True

    def is_finished(self):
        now = timezone.now().date()
        is_finished = now > self.date
        if is_finished:
            BookedDay.objects.filter(reservation=self).delete()
        return is_finished

    is_finished.boolean = True

    def save(self, *args, **kwargs):
        if self.pk is None:
            date = self.date
            time = self.time
            existing_booked_day = BookedDay.objects.filter(
                date=date, time=time
            ).exists()
            if not existing_booked_day:
                super().save(*args, **kwargs)
                BookedDay.objects.create(date=date, time=time, reservation=self)
                return
        return super().save(*args, **kwargs)

reservations/views.py
import datetime
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from restaurants import models as restaurant_models
from reviews import forms as review_forms
from . import models


class CreateError(Exception):
    pass


@login_required
def create(request, restaurant, year, month, day, time, numOfGuests):
    try:
        date_obj = datetime.datetime(year, month, day)
        restaurant = restaurant_models.Restaurant.objects.get(pk=restaurant)
        models.BookedDay.objects.get(
            date=date_obj, time=time, reservation__restaurant=restaurant
        )
        raise CreateError()
    except (restaurant_models.Restaurant.DoesNotExist, CreateError):
        messages.error(request, _("This is the time that has already been reserved."))
        return render(
            request,
            "reservations/choose_detail.html",
            {"restaurant": restaurant.pk, "year": year, "month": month, "day": day},
        )

    except models.BookedDay.DoesNotExist:
        reservation = models.Reservation.objects.create(
            guest=request.user,
            restaurant=restaurant,
            date=date_obj,
            time=time,
            numOfGuests=numOfGuests,
        )
        messages.success(request, _("Reserved Successfully"))
        return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


@login_required
def choose_detail(request, restaurant, year, month, day):
    if request.method == "POST":
        time = request.POST.get("time")
        numOfGuests = request.POST.get("numOfGuests")
        return redirect(
            reverse(
                "reservations:create",
                kwargs={
                    "year": year,
                    "month": month,
                    "day": day,
                    "time": time,
                    "numOfGuests": numOfGuests,
                    "restaurant": restaurant,
                },
            )
        )

    else:
        return render(
            request,
            "reservations/choose_detail.html",
            {"year": year, "month": month, "day": day, "restaurant": restaurant},
        )


def reservation_detail(request, pk):
    reservation = models.Reservation.objects.get(pk=pk)
    if not reservation or (
        reservation.guest != request.user
        and reservation.restaurant.host != request.user
    ):
        raise Http404()
    form = review_forms.CreateReviewForm()
    return render(
        request,
        "reservations/detail.html",
        {"reservation": reservation, "form": form},
    )


def edit_reservation(request, pk, verb):
    reservation = models.Reservation.objects.get_or_none(pk=pk)
    if not reservation or (
        reservation.guest != request.user
        and reservation.restaurant.host != request.user
    ):
        raise Http404()
    if verb == "confirm":
        reservation.status = models.Reservation.STATUS_CONFIRMED
    elif verb == "cancel":
        reservation.status = models.Reservation.STATUS_CANCELED
        models.BookedDay.objects.filter(reservation=reservation).delete()
    reservation.save()
    messages.success(request, _("Reservation Updated"))
    return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))

templates/reservations/choose_detail.html
{% extends "base.html" %}

{% load static i18n %}
{% block page_title %}
Reservation
{% endblock page_title %}

{% block content %}


<div class="md:w-full items-center px-6 container mx-auto pb-10 flex flex-col items-start border p-6 border-white">
    <form method="POST">
        {% csrf_token %}
        <div class="w-full border border-gray-700 rounded-lg mb-2">
            <span class="p-3 text-center font-semibold text-lg block">{%trans "Lunch"%}</span>
            <div class="grid md:grid-cols-7 sm:grid-cols-7 lg:grid-cols-7 mb-3">
                <div class=" text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                    11:00 <input type="radio" name="time" value="11:00" />
                </div>
                <div class="text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                    11:30 <input type="radio" name="time" value="11:30" />
                </div>
                <div class="text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                    12:00 <input type="radio" name="time" value="12:00" />
                </div>
                <div class="text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                    12:30 <input type="radio" name="time" value="12:30" />
                </div>
                <div class="text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                    13:00 <input type="radio" name="time" value="13:00" />
                </div>
                <div class="text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                    13:30 <input type="radio" name="time" value="13:30" />
                </div>
                <div class="text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                    14:00 <input type="radio" name="time" value="14:00" />
                </div>
                <div class="text-center font-medium text-lg bg-gray-100 overflow-hidden border border-gray-200 p-1">
                </div>

            </div>
        </div>

        <div class="w-full border border-gray-700 rounded-lg">
            <span class="p-3 text-center font-semibold text-lg block">{%trans "Dinner"%}</span>
            <div class="grid md:grid-cols-7 sm:grid-cols-7 lg:grid-cols-7 mb-3">
                <div class=" text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                    17:00 <input type="radio" name="time" value="17:00" />
                </div>
                <div class="text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                    17:30 <input type="radio" name="time" value="17:30" />
                </div>
                <div class="text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                    18:00 <input type="radio" name="time" value="18:00" />
                </div>
                <div class="text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                    18:30 <input type="radio" name="time" value="18:30" />
                </div>
                <div class="text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                    19:00 <input type="radio" name="time" value="19:00" />
                </div>
                <div class="text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                    19:30 <input type="radio" name="time" value="19:30" />
                </div>
                <div class="text-center font-medium text-lg bg-white overflow-hidden border border-gray-200 p-1">
                    20:00 <input type="radio" name="time" value="20:00" />
                </div>
                <div class="text-center font-medium text-lg bg-gray-100 overflow-hidden border border-gray-200 p-1">

                </div>
            </div>
        </div>



        <fieldset>
            <span class="p-3 text-center font-semibold text-lg block">{%trans "Number Of Guests"%}</span>
            <input type="number" name="numOfGuests">
        </fieldset>
        <button class="btn-link mt-10" type='submit'>{%trans "Make Reservation"%}</button>
    </form>
</div>
{% endblock content %}

templates/reservations/detail.html
{% extends "base.html" %}
{% load static i18n %}

{% block page_title %}
Reservation {{reservation.date}} {{reservation.time}}
{% endblock page_title %}


{% block content %}

<div class="container mx-auto my-10 flex flex-col">

    <div class="border-t border-l border-r bg-cover bg-center h-56 rounded-t-lg"
        style="background-image: url({{reservation.restaurant.first_photo}});"></div>

    <div class="flex flex-col items-start border-l border-r border-t border-b">
        <div class="font-medium border-b py-8 px-5 w-full">
            {{reservation.date}}
            <span
                class="ml-5 {% if reservation.status == 'pending' %} text-yellow-500 {% elif reservation.status == 'canceled' %} text-red-600 {% else %} text-teal-600 {% endif %}">{{reservation.get_status_display}}</span>
        </div>

        <span class="text-2xl border-b p-5 mt-2 w-full">
            {{reservation.restaurant.name}}
        </span>

        <div class="flex p-5 border-b w-full">
            <div class="flex flex-col items-center">
                {% if request.session.is_hosting %}
                {% include "mixins/user_avatar.html" with user=reservation.guest %}
                <span class="mt-2 text-gray-500">{{reservation.guest.first_name}}</span>
                {% else %}
                {% include "mixins/user_avatar.html" with user=reservation.restaurant.host %}
                <span class="mt-2 text-gray-500">{{reservation.restaurant.host.first_name}}</span>
                {% endif %}


            </div>
            <div class="ml-5 flex flex-col">
                {% if request.session.is_hosting %}
                <span class="font-medium mb-px">{% trans "Contact your Guest" %}</span>
                {% else %}
                <span class="font-medium mb-px">{% trans "Contact your Host" %}</span>
                {% endif %}
                <a href="{% url 'conversations:go' reservation.restaurant.host.pk reservation.guest.pk %}"
                    class="font-medium text-teal-500">{% trans "Send a Message" %}</a>
            </div>
        </div>

        <div class="py-10 px-5">
            {% if not request.session.is_hosting %}
            {% if reservation.status != 'canceled' %}
            {% if reservation.status == 'confirmed' and reservation.is_finished %}
            <span class="font-medium text-2xl text-center w-full block mb-5">{%trans "Write your review"%}</span>
            <form action="{% url 'reviews:create' reservation.restaurant.pk %}" method="POST" class="w-1/2 mx-auto">
                {% csrf_token %}
                {{form}}
                <button class="btn-link mt-5">{%trans "Submit Review"%}</button>
            </form>
            {% else %}
            {% if reservation.status == 'pending' %}
            <a href="{% url 'reservations:edit' reservation.pk 'cancel' %}" class="btn-link block px-5 mb-3">
                {% trans "Cancel Reservation" %}
            </a>
            {% endif %}
            {% endif %}
            {% endif %}
            {% else %}
            {% if reservation.restaurant.host == user  %}
            {% if reservation.status == 'pending' %}
            <a href="{% url 'reservations:edit' reservation.pk 'confirm' %}" class="btn-link px-3 mb-5 mr-10">
                {% trans "Confirm Reservation" %}
            </a>
            <a href="{% url 'reservations:edit' reservation.pk 'cancel' %}" class="btn-link px-5 mb-3">
                {% trans "Cancel Reservation" %}
            </a>
            {% endif %}
            {% endif %}
            {% endif %}
        </div>
    </div>


</div>
{% endblock content %}

templates/reservations/guest_reservation.html
{% extends "base.html" %}
{% load static i18n %}

{% block page_title %}
{{user.first_name}}'s Reservation
{% endblock page_title %}

{% block content %}

<div class="md:w-full px-6 container mx-auto pb-10 flex flex-col items-start border p-6 border-white">
    <h3 class="mb-5 ml-5 text-3xl font-bold">{% trans "Guest" %} {{user.first_name}}{% trans "'s Reservations" %}</h3>
    <div class="md:w-full px-6 container mx-auto pb-10 flex flex-col items-start border p-6 border-gray-400">
        <h3 class="text-2xl mb-5 ml-2">{% trans "Reservations In Progress" %}</h3>
        <div class="grid gap-2 grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 mt-1">
            {% for i in reservation %}
            {% if not i.is_finished %}
            <div class="w-full max-w-sm mx-auto rounded-md shadow-md overflow-hidden">
                <a href="{% url 'reservations:detail' i.pk %}">
                    <div class="flex items-end justify-end h-56 w-full bg-cover"
                        style="background-image: url({{i.restaurant.first_photo}});">
                    </div>
                    <div>
                        <div>
                            <span class="mx-2 my-5">
                                {{i.restaurant.name}}
                            </span>
                            <span
                                class="ml-10 text-right {% if i.status == 'pending' %} text-yellow-500 {% elif i.status == 'canceled' %} text-red-600 {% else %} text-teal-600 {% endif %}">{{i.get_status_display}}</span>
                        </div>

                        <div>
                            <span class="mx-2 my-1 flex flex-col">
                                {% trans "Reservation Date" %} : {{i.date}}
                            </span>
                            <span class="mx-2 my-1 flex flex-col">
                                {% trans "Reservation Time" %} : {{i.time}}
                            </span>
                        </div>

                    </div>

                </a>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class="md:w-full px-6 container mx-auto pb-10 flex flex-col items-start border p-6 border-gray-400">
        <h3 class="text-2xl mb-5 ml-2">{% trans "Finished Reservations" %}</h3>
        <div class="grid gap-2 grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 mt-1">
            {% for i in reservation %}
            {% if i.is_finished %}
            <div class="w-full max-w-sm mx-auto rounded-md shadow-md overflow-hidden">
                <a href="{% url 'reservations:detail' i.pk %}">
                    <div class="flex items-end justify-end h-56 w-full bg-cover"
                        style="background-image: url({{i.restaurant.first_photo}});">
                    </div>
                    <div>
                        <div>
                            <span class="mx-2 my-5">
                                {{i.restaurant.name}}
                            </span>
                            <span
                                class="ml-10 text-right {% if i.status == 'pending' %} text-yellow-500 {% elif i.status == 'canceled' %} text-red-600 {% else %} text-teal-600 {% endif %}">{{i.get_status_display}}</span>
                        </div>

                        <div>
                            <span class="mx-2 my-1 flex flex-col">
                                {% trans "Reservation Date" %} : {{i.date}}
                            </span>
                            <span class="mx-2 my-1 flex flex-col">
                                {% trans "Reservation Time" %} : {{i.time}}
                            </span>
                        </div>

                    </div>
                </a>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

templates/reservations/host_reservation.html
{% extends "base.html" %}
{% load static i18n %}

{% block page_title %}
{{user.first_name}}'s Reservation
{% endblock page_title %}

{% block content %}

<div class="md:w-full px-6 container mx-auto pb-10 flex flex-col items-start border p-6 border-white">

    <h3 class="mb-5 ml-5 text-3xl font-bold">{% trans "Host" %} {{user.first_name}}{% trans "'s Reservations" %}</h3>
    <div class="md:w-full px-6 container mx-auto pb-10 flex flex-col items-start border p-6 border-gray-400">
        <h3 class="text-2xl mb-5 ml-2">{% trans "Reservations In Progress "%}</h3>
        <div class="grid gap-2 grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 mt-1">
            {% for ro in restaurant %}
            {% for i in reservation %}
            {% if ro.name == i.restaurant.name %}
            {% if not i.is_finished %}
            <div class="w-full max-w-sm mx-auto rounded-md shadow-md overflow-hidden">
                <a href="{% url 'reservations:detail' i.pk %}">
                    <div class="flex items-end justify-end h-56 w-full bg-cover"
                        style="background-image: url({{i.restaurant.first_photo}});">
                    </div>
                    <div>
                        <span class="mx-2 my-5">
                            {{i.restaurant.name}}
                        </span>
                        <span
                            class="ml-10 text-right {% if i.status == 'pending' %} text-yellow-500 {% elif i.status == 'canceled' %} text-red-600 {% else %} text-teal-600 {% endif %}">{{i.get_status_display}}</span>
                    </div>
                    <div>
                        <span class="mx-2 my-1 flex flex-col">
                            {% trans "Reservation Date" %} : {{i.date}}
                        </span>
                        <span class="mx-2 my-1 flex flex-col">
                            {% trans "Reservation Time" %} : {{i.time}}
                        </span>
                        <span class="mx-2 my-1 flex flex-col">
                            {% trans "Guest Name" %} : {{i.guest.first_name}}
                        </span>
                        <span class="mx-2 my-1 flex flex-col">
                            {% trans "Number of Guests" %} : {{i.numOfGuests}}
                        </span>
                    </div>



                </a>

            </div>
            {% endif %}
            {% endif %}
            {% endfor %}
            {% endfor %}
        </div>
    </div>

    <div class="md:w-full px-6 container mx-auto pb-10 flex flex-col items-start border p-6 border-gray-400">
        <h3 class="text-2xl mb-5 ml-2">{% trans "Finished Reservations" %}</h3>
        <div class="grid gap-2 grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 mt-1">
            {% for ro in restaurant %}
            {% for i in reservation %}
            {% if ro.name == i.restaurant.name %}
            {% if i.is_finished %}
            <div class="w-full max-w-sm mx-auto rounded-md shadow-md overflow-hidden">
                <a href="{% url 'reservations:detail' i.pk %}">
                    <div class="flex items-end justify-end h-56 w-full bg-cover"
                        style="background-image: url({{i.restaurant.first_photo}});">
                    </div>
                    <div>
                        <span class="mx-2 my-5">
                            {{i.restaurant.name}}
                        </span>
                        <span
                            class="ml-10 text-right {% if i.status == 'pending' %} text-yellow-500 {% elif i.status == 'canceled' %} text-red-600 {% else %} text-teal-600 {% endif %}">{{i.get_status_display}}</span>
                    </div>
                    <div>
                        <span class="mx-2 my-1 flex flex-col">
                            {% trans "Reservation Date" %} : {{i.date}}
                        </span>
                        <span class="mx-2 my-1 flex flex-col">
                            {% trans "Reservation Time" %} : {{i.time}}
                        </span>
                        <span class="mx-2 my-1 flex flex-col">
                            {% trans "Guest Name" %} : {{i.guest.first_name}}
                        </span>
                        <span class="mx-2 my-1 flex flex-col">
                            {% trans "Number of Guests" %} : {{i.numOfGuests}}
                        </span>
                    </div>



                </a>
            </div>
            {% endif %}
            {% endif %}
            {% endfor %}
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/reservations/user_reservation.html
{% extends "base.html" %}

{% block page_title %}
{{user.first_name}}'s Reservation
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="h-full">
    {{user_obj.reservation}}


</div>

{% endblock content %}