config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("restaurants/", include("restaurants.urls", namespace="restaurants")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from restaurants import views as restaurant_views

app_name = "core"

urlpatterns = [
    path("", restaurant_views.HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
    path("guest/<int:pk>/", views.show_guest_reservation, name="guest-reservation"),
    path(
        "host/<int:pk>/",
        views.show_host_reservation,
        name="host-reservation",
    ),
    path("<int:pk>/photos/", views.UserPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:user_pk>/photos/<int:photo_pk>/delete",
        views.delete_photo,
        name="delete-photo",
    ),
]

users/models.py
import uuid
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.mail import send_mail
from django.utils.html import strip_tags
from django.shortcuts import reverse
from django.template.loader import render_to_string
from core import managers as core_managers
from core import models as core_models


class Photo(core_models.TimeStampedModel):

    """ Photo Model Definition """

    file = models.ImageField(upload_to="avatars")
    user = models.ForeignKey("User", related_name="photos", on_delete=models.CASCADE)


class User(AbstractUser):

    """ Custom User Model """

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_OTHER = "other"

    GENDER_CHOICES = (
        (GENDER_MALE, _("Male")),
        (GENDER_FEMALE, _("Female")),
        (GENDER_OTHER, _("Other")),
    )

    LANGUAGE_ENGLISH = "en"
    LANGUAGE_KOREAN = "kr"

    LANGUAGE_CHOICES = (
        (LANGUAGE_ENGLISH, _("English")),
        (LANGUAGE_KOREAN, _("Korean")),
    )

    LOGIN_EMAIL = "email"
    LOGIN_KAKAO = "kakao"

    LOGIN_CHOICES = (
        (LOGIN_EMAIL, "Email"),
        (LOGIN_KAKAO, "Kakao"),
    )

    first_name = models.CharField(_("first name"), max_length=30, blank=True)
    gender = models.CharField(
        _("gender"), choices=GENDER_CHOICES, max_length=10, blank=True
    )
    self_introduction = models.TextField(_("self_introduction"), blank=True)
    birthdate = models.DateField(_("birthdate"), blank=True, null=True)
    language = models.CharField(
        _("language"),
        choices=LANGUAGE_CHOICES,
        max_length=2,
        blank=True,
        default=LANGUAGE_KOREAN,
    )

    email_verified = models.BooleanField(default=False)
    email_secret = models.CharField(max_length=20, default="", blank=True)
    login_method = models.CharField(
        max_length=50, choices=LOGIN_CHOICES, default=LOGIN_EMAIL
    )
    objects = core_managers.CustomUserManager()

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

    def verify_email(self):
        if self.email_verified is False:
            secret = uuid.uuid4().hex[:20]
            self.email_secret = secret
            html_message = render_to_string(
                "emails/verify_email.html", {"secret": secret}
            )
            send_mail(
                _("Verify Your Account"),
                strip_tags(html_message),
                settings.EMAIL_FROM,
                [self.email],
                fail_silently=False,
                html_message=html_message,
            )
            self.save()
        return

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

users/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from . import models


class LoginForm(forms.Form):

    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": _("Email")}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": _("Password")})
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error(
                    "password", forms.ValidationError(_("Password is wrong"))
                )
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError(_("User does not exist")))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("first_name", "last_name", "email")
        widgets = {
            "first_name": forms.TextInput(attrs={"placeholder": _("First Name")}),
            "last_name": forms.TextInput(attrs={"placeholder": _("Last Name")}),
            "email": forms.EmailInput(attrs={"placeholder": _("Email")}),
        }

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": _("Password")})
    )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": _("Confirm Password")})
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError(
                _("That email is already taken"), code="existing_user"
            )
        except models.User.DoesNotExist:
            return email

    def clean_confirm_password(self):
        password = self.cleaned_data.get("password")
        confirm_password = self.cleaned_data.get("confirm_password")
        if password != confirm_password:
            raise forms.ValidationError(_("Password confirmation does not match"))
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("file",)

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        user = models.User.objects.get(pk=pk)
        photo.user = user
        photo.save()

users/views.py
import os
import requests
from django.utils import translation
from django.utils.translation import gettext_lazy as _
from django.http import HttpResponse
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import FormView, DetailView, UpdateView
from django.urls import reverse_lazy
from django.shortcuts import redirect, reverse, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from restaurants import models as restaurant_models
from reservations import models as reservation_models
from . import forms, models, mixins

from django.http import Http404


class LoginView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def log_out(request):
    messages.info(request, _("See you later"))
    logout(request)
    return redirect(reverse("core:home"))


class SignUpView(FormView):

    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        if email == "dbwjddbwjd@gmail.com":
            user.verify_email()
        return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
    except models.User.DoesNotExist:
        pass
    return redirect(reverse("core:home"))


def kakao_login(request):
    client_id = os.environ.get("KAKAO_ID")
    redirect_uri = "http://3.35.68.245/users/login/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code"
    )


class KakaoException(Exception):
    pass


def kakao_callback(request):
    try:
        code = request.GET.get("code")
        client_id = os.environ.get("KAKAO_ID")
        redirect_uri = "http://3.35.68.245/users/login/kakao/callback"
        token_request = requests.get(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={redirect_uri}&code={code}"
        )
        token_json = token_request.json()
        error = token_json.get("error", None)
        if error is not None:
            raise KakaoException(_("Can't get authorization code."))
        access_token = token_json.get("access_token")
        profile_request = requests.get(
            "https://kapi.kakao.com/v2/user/me",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        profile_json = profile_request.json()

        kakao_account = profile_json.get("kakao_account")
        email = kakao_account.get("email", None)

        if email is None:
            raise KakaoException(_("Please also give me your email"))
        properties = profile_json.get("properties")
        nickname = properties.get("nickname")
        try:
            user = models.User.objects.get(email=email)
            if user.login_method != models.User.LOGIN_KAKAO:
                raise KakaoException(f"Please login with: {user.login_method}")
        except models.User.DoesNotExist:
            user = models.User.objects.create(
                email=email,
                username=email,
                first_name=nickname,
                login_method=models.User.LOGIN_KAKAO,
                email_verified=True,
            )
            user.set_unusable_password()
            user.save()
        messages.success(request, f"Welcome back {user.first_name}")
        login(request, user)
        return redirect(reverse("core:home"))
    except KakaoException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


class UserProfileView(DetailView):

    model = models.User
    context_object_name = "user_obj"


class UpdateProfileView(mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):
    model = models.User
    template_name = "users/update-profile.html"
    fields = (
        "first_name",
        "last_name",
        "email",
        "gender",
        "language",
        "birthdate",
        "self_introduction",
    )
    success_message = _("Profile Updated")

    def get_object(self, queryset=None):
        return self.request.user


class UpdatePasswordView(
    mixins.EmailLoginOnlyView,
    mixins.LoggedInOnlyView,
    SuccessMessageMixin,
    PasswordChangeView,
):

    template_name = "users/update-password.html"
    success_message = _("Password Updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()


@login_required
def switch_hosting(request):
    try:
        del request.session["is_hosting"]
    except KeyError:
        request.session["is_hosting"] = True
    return redirect(reverse("core:home"))


def switch_language(request):
    lang = request.GET.get("lang", None)
    if lang is not None:
        request.session[translation.LANGUAGE_SESSION_KEY] = lang
    return HttpResponse(status=200)


def show_guest_reservation(request, *args, **kwargs):
    user = request.user
    reservation = reservation_models.Reservation.objects.filter(guest=user)
    return render(
        request,
        "reservations/guest_reservation.html",
        {"reservation": reservation, "user": user},
    )


def show_host_reservation(request, *args, **kwargs):
    user = request.user
    restaurant = restaurant_models.Restaurant.objects.filter(host=user)
    reservation = reservation_models.Reservation.objects.all()

    return render(
        request,
        "reservations/host_reservation.html",
        {"reservation": reservation, "restaurant": restaurant},
    )

    # 사진


class UserPhotosView(mixins.LoggedInOnlyView, DetailView):

    model = models.User
    template_name = "users/users_photos.html"

    def get_object(self, queryset=None):
        user = super().get_object(queryset=queryset)
        if user.pk != self.request.user.pk:
            raise Http404()
        return user


@login_required
def delete_photo(request, user_pk, photo_pk):
    user = request.user
    try:
        if user.pk != user.pk:
            messages.error(request, _("Can't delete that photo"))
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, _("Photo Deleted"))
        return redirect(reverse("users:photos", kwargs={"pk": user_pk}))
    except models.User.DoesNotExist:
        return redirect(reverse("core:home"))


class AddPhotoView(mixins.LoggedInOnlyView, FormView):

    template_name = "users/users_photo_create.html"
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, _("Photo Uploaded"))
        return redirect(reverse("users:photos", kwargs={"pk": pk}))

templates/users/login.html
{% extends "base.html" %}
{% load static i18n %}
{% block page_title %}
Log In
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

    {% include 'partials/social_login.html' %}

    {% include 'mixins/auth/auth_form.html' with form=form cta="Log in" %}

    <div class="mt-5">
        <span class="mr-2">{%trans "Don't you have an account yet?"%}</span>
        <a href="{% url 'users:signup' %}" class="text-teal-500 font-medium">{%trans "Sign up"%}</a>
    </div>
</div>
{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}
{% load static i18n %}

{% block page_title %}
Sign Up
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

    {% include 'partials/social_login.html' %}

    {% include 'mixins/auth/auth_form.html' with form=form cta="Sign up" %}

    <div class="mt-5">
        <span class="mr-2">{%trans "Do you already have an account?"%}</span>
        <a href="{% url 'users:login' %}" class="text-teal-500 font-medium">{%trans "Log in"%}</a>
    </div>

</div>
{% endblock content %}

templates/users/update-password.html
{% extends "base.html" %}
{% load static i18n %}
{% block page_title %}
Update Password
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="min-h-75vh">
    <div
        class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/auth/auth_form.html' with form=form cta="Update Password" %}
    </div>
</div>
{% endblock content %}

templates/users/update-profile.html
{% extends "base.html" %}
{% load static i18n %}
{% block page_title %}
Update Profile
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
    <div class="mt-5">
        <a href="{% url 'users:photos' user.pk %}" class="text-teal-500 font-medium">{% trans "Edit Photos" %}</a>
    </div>
    {% include 'mixins/auth/auth_form.html' with form=form cta="Update profile" %}
    {% if object.login_method == "email" %}
    <div class="mt-5">
        <a href="{% url 'users:password' %}" class="text-teal-500 font-medium">{%trans "Change Password"%}</a>
    </div>
    {% endif %}

</div>
{% endblock content %}

templates/users/user_detail.html
{% extends "base.html" %}
{% load static i18n %}
{% block page_title %}
{{user_obj.first_name}}'s Profile
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="h-full">
    <div
        class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include "mixins/user_avatar.html" with suer=user_obj %}
        <div class="flex items-center">
            <span class="text-3xl mt-1">{{user_obj.first_name}}</span>
            {% if user_obj.superhost %}
            <i class="fas fa-check-circle text-teal-400 ml-1"></i>
            {% endif %}
        </div>

        <span class="text-lg mb-5">{{user_obj.self_introduction}}</span>

        {% if user == user_obj %}
        <a href="{% url 'users:update' %}" class="btn-link">{%trans "Edit Profile"%}</a>
        {% endif %}

    </div>

    {% if user_obj.restaurants.all.count > 0 %}
    <div class="container mx-auto pb-10 flex flex-col items-center">
        <h3 class="mb-12 text-2xl">{{user_obj.first_name}}{%trans "'s Restaurants"%}</h3>
        <div class="grid gap-2 w-full grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 mt-1">
            {% for restaurant in user_obj.restaurants.all %}
            {% include 'mixins/restaurant_card.html' with restaurant=restaurant %}
            {% endfor %}
        </div>
    </div>
    {% endif %}

</div>

{% endblock content %}

templates/users/users_photo_create.html
{% extends "base.html" %}

{% block page_title %}
Upload Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">


    {% include 'mixins/auth/auth_form.html' with form=form cta="Upload photo" %}


</div>
{% endblock content %}

templates/users/users_photos.html
{% extends "base.html" %}
{% load static i18n %}
{% block page_title %}
Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container mx-auto my-10 flex flex-col">

    {% if user.photos.all %}
    <div class="my-10 w-full">
    </div>
    {% else %}
    <div class="my-10 w-full">
        <a href="{% url 'users:add-photo' user.pk %}" class="btn-link w-1/6 block">{%trans "Upload Photo"%}</a>
    </div>
    {% endif %}


    {% for photo in user.photos.all %}
    <div class="mb-5 border p-6 gorder-gray-400 flex justify-between content-center">
        <div class="flex items-start">
            <img src="{{photo.file.url}}" class="w-32 h-32" />
        </div>
        <div class=" flex flex-col w-1/5  content-center">
            <a class="btn-link bg-red-700" href="{% url 'users:delete-photo' user.pk photo.pk %}">{%trans "Delete"%}</a>
        </div>
    </div>
    {% endfor %}

    <div class="flex justify-center mt-5">
        <a href="{% url 'users:update' %}" class="text-teal-500 font-medium text-2xl">
            {% trans "Back to edit user" %}
        </a>
    </div>

</div>
{% endblock content %}